apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observability-app
  template:
    metadata:
      labels:
        app: observability-app
    spec:
      containers:
      - name: observability-app
        image: localhost:5000/observability-app:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: observability-app
  labels:
    app: observability-app
spec:
  selector:
    app: observability-app
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080
