apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observability-app-service-monitor
spec:
  selector:
    matchLabels:
      app: observability-app
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
